### ISSUE TITLE
Luk 7:28 UDB

### ISSUE THREAD

**Issue by lrsallee** [Door43/udb-en#10]
I am struggling with the implications of the rendering of this passage:

"I tell you that from among all the people who have ever lived, there is no one who is greater than John. However, God considers even the most insignificant people whom he has agreed to rule over to be greater than John."

Jesus has already said John was the greatest person alive ("born of a woman" may be stated to somehow exclude Jesus as eternal). I can understand how a glorified, sinless person in the kingdom will be greater. But certainly John also "let God rule" in his life, and was filled with the Holy Spirit from birth. So it defies logic to say that the most insignificant person in this life is more important than John if they "let God rule in their lives." At best, a really, really good person might be equal to John. As written, this makes no sense to me. 

It seems to me that Jesus is possibly referring to the future state of any person in the eternal kingdom of God is greater than even the most revered prophet who is still living in this corrupt, sinful earth. Or, he is at the least referring to the beginning of the New Covenant relationship which Jesus will establish. I believes these would be agreeable to all the major theological bents. 

Can we reword this somehow to make it focus more on a change to something new in the future? Or if not, to remove the reference to the generic idea of letting God rule, which would apply to all time periods.

**Comment by TomWarren** [comment]
I worked on it: 

\v 28 I tell you that from among all the people who have ever lived, there is no one was greater than John. Yet, it is true that when God's reign is made complete, even the most insignificant people in that kingdom will be considered to be greater than John because, then, they will obey God in everything they do.

**Comment by pjoakes** [comment]
Tom,
I believe that the UDB avoids the word “kingdom,” thus the problem with the wording here with this concept and the specialized way that Jesus uses the term here. So adding the word back in just puts us back where we started and doesn’t solve the problem. Please try to find a way that doesn’t use the word “kingdom.”

Thanks,

Perry

Perry Oakes, Ph.D.
Chief Language Officer
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>

[cid:image002.png@01D116FB.66313BC0]

On May 13, 2016, at 5:06 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


I worked on it:

\v 28 I tell you that from among all the people who have ever lived, there is no one was greater than John. Yet, it is true that when God's reign is made complete, even the most insignificant people in that kingdom will be considered to be greater than John because, then, they will obey God in everything they do.

**Comment by TomWarren** [comment]
Another try. Hard not to say kingdom when you are describing kingdom. 

\v 28 I tell you that from among all the people who have ever lived, there is no one was greater than John. Yet, it is true that, one day, when God exercises his power and authority over all things and everyone, even the most insignificant people will be considered to be greater than John, because, then, they will obey God in everything they do.

**Comment by lrsallee** [comment]
Tom,

Not sure from Perry’s perspective, but that works for me. It solves the logical problem that I was struggling with in the TN’s.

Thanks.

Larry

**Comment by pjoakes** [comment]
Right. Welcome to the world of Bible translation. I think this will work,  although I think I would replace "one day" with inserting "completely " in the sentence,  to move the emphasis from time to quality. What do you think?



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by TomWarren** [comment]
The tension between the authority of God's kingdom now as against his kingdom in the future—the now but not yet fully implemented—is the tightrope here. I need to think about this a bit more. 
My impression is that either "that day" or "completely" are wrestling with the same point of tension. 
In what way is God's kingdom not now over all things and everyone completely? Or how will it be established "one day" but it is not now what it will be? In the sense that God has established a time in which his kingdom is now but not fully implemented, we live in G.E. Ladd's (Theology of the New Testament) tension of the kingdom that in inaugurated (by the resurrection of Christ), but is not fully revealed—the "now but not yet" tension (Christ has not yet returned) . "We love him, though we do not see him now." I was thinking that "one day" brings us to the point of implementation of the complete revelation of God's rule and kingdom on earth as in heaven. Completely may suggest that God does not now rule completely (perhaps "one day" suggests the same problem). I think "one day" avoids the problem that God doesn't rule over everything now. Which we believe he does. More time to think...

**Comment by pjoakes** [comment]
Tom,

Yes, that’s exactly the problem, and why it’s so hard to specify the meaning behind “kingdom” here. Is this the same tension as between old covenant/new covenant? I have heard this verse also discussed in that context. Jesus is beginning something new which is not yet fully implemented at that time (or even now), so there is both a time and a quality difference between John’s experience of God and that of believers post-resurrection. May God give you wisdom!

Perry


Perry Oakes, Ph.D.
Chief Language Officer
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>

[cid:image002.png@01D116FB.66313BC0]

On May 15, 2016, at 9:56 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


The tension between the authority of God's kingdom now as against his kingdom in the future—the now but not yet fully implemented—is the tightrope here. I need to think about this a bit more.
My impression is that either "that day" or "completely" are wrestling with the same point of tension.
In what way is God's kingdom not now over all things and everyone completely? Or how will it be established "one day" but it is not now what it will be? In the sense that God has established a time in which his kingdom is now but not fully implemented, we live in G.E. Ladd's (Theology of the New Testament) tension of the kingdom that in inaugurated (by the resurrection of Christ), but is not fully revealed—the "now but not yet" tension (Christ has not yet returned) . "We love him, though we do not see him now." I was thinking that "one day" brings us to the point of implementation of the complete revelation of God's rule and kingdom on earth as in heaven. Completely may suggest that God does not now rule completely (perhaps "one day" suggests the same problem). I think "one day" avoids the problem that God doesn't rule over everything now. Which we believe he does. More time to think...

**Comment by TomWarren** [comment]
The other issue is that the UDB uses "kingdom" 13 times (using USM search).

**Comment by pjoakes** [comment]
Yes - the problem with crowdsourcing a translation.

Perry Oakes, Ph.D.
Chief Language Officer
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>

[cid:image002.png@01D116FB.66313BC0]

On May 16, 2016, at 8:13 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


The other issue is that the UDB uses "kingdom" 13 times (using USM search).

**Comment by TomWarren** [comment]
Another try, after pondering a bit. Luke 7:28 UDB
\v 28 I tell you that from among all the people who have ever lived, there is no one greater than John. Yet, while God now rules over everyone and everything, his rule will be confirmed by Christ's return. His opponents will be defeated, and he will rule forever. Then, even the most insignificant people who live with God where he dwells, will be even greater than John.
