### ISSUE TITLE
PSA 2:4 UDB Yahweh to Lord

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#112]
PSA 2:4 UDB Yahweh ridicules those rules.

Hebrew has Adonai, and ULB has "the Lord".
Could UDB be changed to "the Lord"?

**Comment by SusanQuigley** [comment]
I just read that many Hebrew manuscripts have "Yahweh,"  but the Masoretic text has "Adonai." That may explain the difference. But I think the ULB and UDB should reflect the same texts.

**Comment by TomWarren** [comment]
We usually follow the MT in cases like this where the rendering could go either way, but the MT is not . Some support that Adonai was substituted for Yahweh because of the ineffable quality of the divine name (that would not be spoken or written by devout Jewish scribes). 
We can leave "the Lord" here. It may be well to alert the MTT that this is not the name, Yahweh, as Yahweh is often rendered "LORD" but not here.  This is the word for Lord, Master, Owner, Ruler and the like. 

The UDB PSA 2:4 now reads: 
\v 4 But the one who sits on his throne in heaven laughs at them;
\q2 the Lord ridicules those rulers.
The ULB PSA 2:4 now reads: 
\v 4 He who sits in the heavens will sneer at them;
\q the Lord mocks them.

Thanks

**Comment by SusanQuigley** [comment]
Thank you, Tom. There is a link to the tW page for Lord, which explains that in the ULB and UDB, "Lord" is never used as a translation of Yahweh.

**Comment by pjoakes** [comment]
Right, so there is no need to alert the MTT that this is not Yahweh, because ULB and UDB do not confuse that with “Lord."

Perry Oakes, Ph.D.
Chief Language Officer
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>

[cid:image002.png@01D116FB.66313BC0]

On Aug 25, 2016, at 9:31 AM, SusanQuigley <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you, Tom. There is a link to the tW page for Lord, which explains that in the ULB and UDB, "Lord" is never used as a translation of Yahweh.

**Comment by TomWarren** [comment]
I do think that the distinction between Yahweh and Adonai is significant. We often assume that the MTT does not know about these distinctions, but any commentary or study bible would most surely address the names of God in the OT. It seems to me that each of us have our vision of what the MTT knows or doesn't know, but each language group would be different. What may clarify for one could bring new questions for another Iwho less schooled or less knowledgeable about these questions.

**Comment by SusanQuigley** [comment]
I don't think we would want a note every time the word "Lord" occurs saying that the Hebrew word is not Yahweh. However, maybe it would be good to say something here.
The first chunk talks about Yahweh and his Messiah, and this chunk starts out with "He" and "the Lord".
We have the following note:
**He ... the Lord** - These phrases refer to Yahweh.
Maybe I should change it to this:
**He ... the Lord** - These phrases refer to Yahweh. Yahweh is often called "the Lord" but the words for "Yahweh" and "the Lord" are different.

**Comment by TomWarren** [comment]
It is problematic to identify every name of God in the OT (or NT for that matter). We are not writing a study bible, and there may be places where we identify these nuances in the names of God and when we assume that the MTT would have access to other tools that would give them help.  The Hippocratic Oath says that doctors should "do no harm" and I think that is a good principle to follow. Do not confuse or complicate, but at the same time do not be oblique. Thanks, good discussion.
