### ISSUE TITLE
PSA 52:9  hope vs proclaim

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#121]
PSA 52:9
ULB: I will **hope** in your name, for it is good
UDB: I will **proclaim** that you are good

Could these two be the same? I don't know which is better.

**Comment by TomWarren** [comment]
The UDB of PSA 52:9 now reads: 
\v 9 God, I will always thank you for everything you have done.
\q2 I will wait patiently for you, because you are so good, 
\q2 especially when I stand before your faithful people.

The ULB of PSA 52:9 now reads: 
\v 9 I will give you thanks forever for what you have done.
\q I will wait for your name, because it is good,
\q in the presence of your godly people. 

Previous read "hope" in ULB is rendering Heb "wait for". The UDB "proclaim" seems to be rendering the phrase  in HEB "before your godly people" and is supplying the verb "**will proclaim** in the presence of your faithful people "
