### ISSUE TITLE
PSA 55:19  UDB "hear them" vs "hear me"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#123]
ULB God ... will hear them 
UDB he will listen to me

I just realized the ULB and UDB have different objects.

**Comment by TomWarren** [comment]
Vs 19 seems to be referring back to VS 18, to those "who fought against me" and the ULB seems correct. 
The UDB now reads in PSA 55:18-19
\v 18 He saves my life and makes me safe
\q1 when I am fighting a terrible battle against my enemies.
\q2 There are many enemies coming to fight against me!

\s5
\q1
\v 19 God is the one who has ruled everything forever,
\q2 and he will put those who fought against me in their place.
\q1 He will cause my enemies to be defeated and disgraced
\q2 because they do not change their evil behavior
\q2 and because they do not have any respect for God.

Thanks. 

Tom

**Comment by SusanQuigley** [comment]
Thank you.
