### ISSUE TITLE
PSA 56:13 UDB in the light that shines on those

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#124]
ULB: so that I may walk before God in the light of the living.
UDB: I will continue to live in your presence in **the light that shines** on those who are alive.

The UDB keeps the "light" figure and expands it with "shines."  Could it be expressed in the UDB without the figure? I'm really not sure what "light" is a figure for, what its relationship is to the word "living," and what the purpose of the phrase is (how it relates to the previous phrase). These translations keep the light figure, but they have different relationships between light and "living": "the light of the living" "the light of life" "your life-giving light"

Here are some ideas  for translating it without the figure.
**If light is a metaphor for joy:**  "I will continue to live in your presence with the joy of those who are alive."
**If light is a metonym for life:**  "I will continue to live in your presence and be fully alive." 
**If "the light of life" is a metonym for giving life:** 
"I will continue to live in your presence with the life that enables people to live" or 
"I will continue to live in your presences with the life that those who are alive receive from you" or
"I will continue to live in your presences with the life that that you give."

**Comment by TomWarren** [comment]
From a purely grammatical POV, there are similar issues with the Reflexive genitive, "light of light" with and there are many possible renderings. 
Light that gives lift. Light that is generated from life. Light that creates life. 
The simplest is to pick one (most popular) and run with it. 
Similar problem with "word of Christ" word which Christ preaches, word about Christ, word that comes from Christ, etc. 

I made a choice here. If you have a suggestion that is stronger, I am willing to change it

UDB PSA 56:13, now reads: 
\v 13 because you have rescued me from being killed;
\q2 you have kept me from stumbling.
\q2 As a result, I will continue to live with God every day, in his light that gives me life.

**Comment by SusanQuigley** [comment]
Ok. Thanks for going with the idea of light that gives life. I think it's better than what the UDB had before. I think "his light that gives me light" is still a figure of speech because I can't think of any literal light that gives or causes life. It's God who make people live. But I can deal with that in the notes.

**in the light of the living** - "in your light that makes people live." Here "the light of the living" probably represents God's enabling people to live. AT: "with the life that you give" or "because you enable me to live" (See: Metonymy)
