### ISSUE TITLE
NUM 11:4-6 UDB verse numbering is different.

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#128]
The verse numbering in the UDB is different than in other versions.
UDB puts "we remember the fish ..." in verse 6, while other versions put it in verse 5.
Other versions start verse 6 with "Now we are weak" or "Now we have lost our appetite."

**Comment by TomWarren** [comment]
THE UDB of NUM 11:4-6 is now aligned with the ULB:
\v 4 Then some troublemakers from other people groups who were traveling with the Israelites began to want better food. And when they started complaining the Israelite people also started to complain. They said, "We wish we had some meat to eat!
\v 5 We remember the fish that we ate while we were in Egypt, fish that was given to us without cost. And we had all the cucumbers, melons, leeks, onions, and garlic we could eat.
\v 6 But now we do not have any strength, because all we have to eat is this manna!"

**Comment by SusanQuigley** [comment]
Thank you.
