### ISSUE TITLE
Rom 6:6 

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/udb-en#13]
I’m facilitating at a MAST in Brazil working with Paul & Linda Fahnestock.  Paul and I and one of our translators agreed that we’d like to kick the UDB translation of Romans 6:6 up the line for reevaluation.  “God views us sinners as having died on the cross with Christ so that he might destroy us, in order that we might no longer have to sin.”  We’re concerned that UDB’s “that he might destroy us” vs ULB’s “in order that the body of sin might be destroyed” might be adding a meaning that is not in the original.

**Comment by pohlig** [comment]
Well, it could at least be misinterpreted. I agree that we need to look at
it.
Thanks for the alert.
Jim

**Comment by pohlig** [comment]
I fixed it. It now reads, "God views us sinners as having died on the cross with Christ, in order that our sinful nature might be destroyed. As a result, we no longer have to sin."

**Comment by pjoakes** [comment]
Jim,

This puts the verb “destroyed” back into the passive - would it be too much to say, “in order that he might destroy our sinful nature.”? Is that making God too much of an active agent?

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On May 17, 2016, at 9:58 PM, pohlig <notifications@github.com<mailto:notifications@github.com>> wrote:


I fixed it. It now reads, "God views us sinners as having died on the cross with Christ, in order that our sinful nature might be destroyed. As a result, we no longer have to sin."

**Comment by pohlig** [comment]
I have changed the phrase to, "in order to put an end to our sinful nature." The Greek verb katargeo is not quite "destroy." It is rather on a more official level: "nullify," "abolish." So I have put the expression into the active voice (thanks, Perry, for the reminder), and have selected what I hope is an easier expression for MTTs than "nullify" or "abolish."

**Comment by mgeurink** [comment]
Thanks all.  That translation looks great.

**Comment by pjoakes** [comment]
Thanks, Jim - looks great.

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On May 18, 2016, at 8:14 PM, pohlig <notifications@github.com<mailto:notifications@github.com>> wrote:


I have changed the phrase to, "in order to put an end to our sinful nature." The Greek verb katargeo is not quite "destroy." It is rather on a more official level: "nullify," "abolish." So I have put the expression into the active voice (thanks, Perry, for the reminder), and have selected what I hope is an easier expression for MTTs than "nullify" or "abolish."
