### ISSUE TITLE
Numbers 12:1-2 UDB Too much in UDB? 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#130]
Numbers 12:1-2 The UDB 
The UDB has this sentence, but I wonder if it is more than we know:
"**They told people that they were saying that because** Moses had married a woman who was a descendant of the Cush people group, but they were really saying that because they were jealous."

The UDB makes it sound like Aaron and Miriam deceitfully explained to the people why they were asking the questions about his authority. But I don't see any need for saying that that explained to the people why the said what they did.  They may have publicly criticized Moses having a Cushite wife, while their complaints about his authority in verse 2 may have been in private. 

Maybe something like one of these would be good for the UDB. These translations explain why Miriam and Aaron were criticizing Moses (because they were jealous his authority) but they do not have Miriam and Aaron explaining anything to the people. 

1-2 Moses' older sister Miriam and his older brother Aaron were jealous of Moses and said "Is Moses the only one to whom Yahweh has spoken messages to tell to us? Does Yahweh not speak messages to us two also?" And they criticized Moses for marrying a woman who was a descendant of the Cush people group. 

Or 

1 Moses' older sister Miriam and his older brother Aaron criticized him for marrying a woman who was a descendant of the Cush people group. 2 They did this because they were jealous of Moses, saying "Is Moses the only one to whom Yahweh has spoken messages to tell to us? Does Yahweh not speak messages to us two also?"

**Comment by TomWarren** [comment]
There was quite a bit of info that was not substantiated nor part of the ULB. So this is a pared-down version, moving through vs 3, as well. 
Hope this helps. 

The UDB of Num 12:1-3 now reads: 
\v 1-2 Moses' older sister Miriam and his older brother Aaron were saying this: "Is Moses the only one to whom Yahweh has spoken messages to tell to us? Does Yahweh not speak messages through us two also?" They told people that they were saying that because Moses had married a woman who was a descendant of the Cush people group. And Yahweh heard Miriam and Aaron complaining about Moses. 
\p
\v 3 The truth was that Moses was a very humble person. He was more humble than anyone else on the earth.

**Comment by SusanQuigley** [comment]
That helps. Thank you.
