### ISSUE TITLE
Lev 24:7 UDB  in some gold cups

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#143]
Along each row, place **in some gold cups** some pure incense to be burned as an offering to me instead of the bread.

It looks like the gold cups are speculation that originated in the TFT.  It's useful for showing that the incense was not actually put on the bread itself. (I've always wondered how unpleasant it must be for the priests to eat bread that had incense on it.) Perhaps this would work to show that the incense was not actually on the bread.

**Next to each row, place some pure incense** to be burned as an offering to me instead of the bread.

**Comment by TomWarren** [comment]
But the incense and the bread were on a gold table. Would there be an issue? 
\v 6 Then you must set them in two rows, six in a row, on the table of pure gold before Yahweh.

**Comment by TomWarren** [comment]
I get queasy when we add details that are impossible to be sure of.

**Comment by SusanQuigley** [comment]
So will you be deleting "in some gold cups" from 24:7 of the UDB? No change is showing up yet on the tN page.

**Comment by TomWarren** [comment]
Here is the UDB LEV 24:7-8 -- hope this is ok. I brought the gold table into vs 7.  

\v 7 Along each row, place on the gold table some pure incense to be burned as an offering to me instead of the bread.
\v 8 The priests must put new loaves of bread on the table each Sabbath day, to signify the covenant that will never end, which I have made with you Israelites.

There you go. Thanks so much. 
TW

**Comment by SusanQuigley** [comment]
That works well. Thank you.
