### ISSUE TITLE
JDG 17:4 unclear

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#148]
"After he gave the silver to his mother, she took two hundred pieces and gave them to a metal worker. With the silver that man made a carved figure and a cast metal figure, and gave them to Micah. Micah put them in his house."

It seems that it could be misinterpreted here that the carved wooden figure was made out of the silver.

**Comment by TomWarren** [comment]
The carved image, פֶּסֶל (pesel)  is an carved image made from wood or from metal.  Since the metal was given to a "metal worker" for the purpose of making idols, it would be assumed that the image was carved out of some form of metal. 
Someone changed the text from "carved figure" to "carved wooden figure."  It is noted that most modern versions leave it "carved figure". The context seems clear that the object was made of metal. It would not be necessary to say that it was "wooden" and may in fact be against the context. 
The ULB now reads: 
\v 4 When he restored the money to his mother, his mother took two hundred pieces of silver and gave them to a metal worker who made them a carved figure and a cast metal figure. It was placed in the house of Micah.
Thanks,

**Comment by kim-putter** [comment]
Hey Tom,

Looks good. Verse 3 though also needs to be updated it the ULB to remove "wooden."
