### ISSUE TITLE
Luk 11:11 UDB - missing bread

### ISSUE THREAD

**Issue by lrsallee** [Door43/udb-en#15]
The UDB skips the stone for bread example that is the first of the three pairs.

**Comment by TomWarren** [comment]
Most MSS include the phrase, "bread, does not give him a stone instead", but the shorter reader is to be preferred; it appears to be a harmonization with Matthew 7:9. (supported by some of the best mss: p45, 75, B 1241 pc sy5 and sa). Most modern translations have the shorter reading. I will make a footnote for this verse.

**Comment by TomWarren** [comment]
Here is the footnote at the end of vs 11: 
\v 11  Which father among you, if your son asks for a fish, will give him a snake instead of a fish? \f + \ft The best ancient copies have the shorter reading, which we follow here. Some ancient copies have the longer reading, which also is found in Matthew 7:9 \fqa 'a loaf of bread, will give him a stone.' \f*

**Comment by TomWarren** [comment]
Here is the pure footnote from the USFM:
[1]The best ancient copies have the shorter reading, which we follow here. Some ancient copies have the longer reading, which also is found in Matthew 7:9, 'a loaf of bread, will give him a stone.'

**Comment by lrsallee** [comment]
OK, that works. Thanks for adding that.
