### ISSUE TITLE
ISA 51:8 UDB  Who will God save?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#162]
7 Listen to me, you who know what is right, you people who have my law in your heart:
Do not fear the insults of men, nor be disheartened by their abuse.
8 because some day they will be destroyed
like clothing that moths have eaten,
like wool garments that have been eaten by worms.
I will save **them**, and **they** will be saved forever."

Could "them" and "they" in the last line be changed to "you"?

**Comment by TomWarren** [comment]
This is one of the perplexingly large issues with the UDB, the shifting from second to first or third person. 
The phrase about "my righteousness will last forever" was not in the UDB, and was added:
UDB ISA 51:8 now reads:
\v 8 because some day they will be destroyed
\q2 like clothing that moths have eaten,
\q1 like wool garments that have been eaten by worms.
\q2 Everyone will know what I do and I will always do what is right; 
\q2 and I will save you, and you will be saved forever."

Hope that helps.

**Comment by SusanQuigley** [comment]
Thanks, Tom.

In 51:6 the UDB has " I will rule you righteously forever"
Would you want the part about God's righteousness to be the same in 6 and 8?

**Comment by TomWarren** [comment]
The UDB of ISA 51:6c now reads:
\q1 But I will rescue you, and you will remain free forever,
\q2 and everyone will know what I do, and I will always do what is right.

Thanks.
