### ISSUE TITLE
PRO 20:5

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#169]
The purposes within a person's life are like the deep waters of the ocean,
but a person who has understanding is able to draw them out and help bring them to pass. 

It seems the "deep waters" spoken of in the first line refers to the waters of a deep well that is underground and to ocean waters.

**Comment by TomWarren** [comment]
There seemed to be an addition to the text, "will help bring them to pass" which is not in the text. 
Deep means "unsearchable" or beyond knowing (due to unattainability, or complexity, or extent to distance to the source).

Deep waters of an ocean may work here. The challenge is that many cultures in arid climates don't have an ocean or even bodies of water, only streams or wells. A note about the nature of "deep bodies of water" may help the MTT.

The UDB had an addition that was removed, "and help to bring them to pass".

The UDB of PRO 20:5 now reads:
\v 5 The purposes within someone's life are like the deep waters of the ocean,
\q2 but a person who has understanding is able to draw them out.

**Comment by kim-putter** [comment]
Sorry I stated that wrong above. What I meant is that most commentaries  interpret the "deep waters" as being a deep well rather than the ocean.

**Comment by TomWarren** [comment]
That  may be a better image for the MTT to understand. 
the UDB of PRO 20:5 now reads:
\v 5 The purposes within a person's life are like waters in a deep well,
\q2 but a person who has understanding is able to draw them out.
