### ISSUE TITLE
2JN 1:1 because of what we know about Christ is true!

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#17]
2JN 1:1 because of what we know about Christ is true!
Please delete "of".

**Comment by TomWarren** [comment]
Took out the errant "of" here is the UDB now:
\v 1 You all know me as the chief Elder. I am writing this letter to you believers, the congregation that I love so much. God has chosen you, and I love you because what we know about Christ is true! Not only do I myself love you, but all those who know and accept the true message that Jesus taught also love you!

**Comment by SusanQuigley** [comment]
Thank you, Tom.
Susan

On Jun 6, 2016, at 1:51 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


Took out the errant "of" here is the UDB now:
\v 1 You all know me as the chief Elder. I am writing this letter to you believers, the congregation that I love so much. God has chosen you, and I love you because what we know about Christ is true! Not only do I myself love you, but all those who know and accept the true message that Jesus taught also love you!
