### ISSUE TITLE
Est 9:22 UDB  "a time of great joy"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#183]
They would remember it as the month in which they changed from being sad to **being a time of great joy.** 

Could "being a time of great joy" be changed to "being very joyful" or "being very happy"?

**Comment by TomWarren** [comment]
The ULB of EST 9:22 now reads:
\v 22 These were the days when the Jews got relief from their enemies, and the month when their sorrow turned to joy, and mourning into a day of celebration. They were to make them days of feasting and gladness, and of sending gifts of food to one another, and gifts to the poor.

**Comment by SusanQuigley** [comment]
Tom, this comment was for the UDB. 
The difficulty I have with the UDB is the idea of **people** changing from being sad (having a certain emotion) to being a **time**.  Either **people** change from being sad to joyful, or the **time** changes from being a time of sadness to a time of great joy.

**Comment by TomWarren** [comment]
The UDB was revised to carry the content of the ULB. 
The UDB of EST 9:22 now reads:
\v 22 because those were the days when the Jews got victory over their enemies. It was in that month that their sorrow was turned to joy. Mordecai's letter told them that they should celebrate on those days by feasting and giving gifts of food to each other and especially to the poor people. 

Thanks,
TW
