### ISSUE TITLE
Job 26:5-14 UDB vs ULB Who is speaking?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#189]
26:5 UDB: **Bildad replied,** "Because the spirits of dead people are afraid,

In the ULB, Job 26 is all Job speaking.
In the UDB Job 26 starts with Job, and switches to Bildad in 26:5. The rest of the chapter is all Bildad speaking.

Job 27:1 UDB Job **replied** to his three friends by saying this:
If the UDB is changed so that it is Job speaking in 26:5-14, then perhaps it would be good to change "this" to "Job continued speaking" or "Job continued by saying"

**Comment by TomWarren** [comment]
The UDB is now aligned with the ULB (and the NIV), 

The UDB of JOB 26:4-5 (where the quotation marks were) now reads:
\v 4 Who helped you to say all those great things?
\q2 Who inspired you to speak like you did?


\s5
\q1
\v 5 Because the spirits of dead people are afraid,
\q2 they tremble in the waters that are deep under the earth.
