### ISSUE TITLE
Job 30:28 ULB vs UDB 'darkened skin" or discouraged"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#199]
Job 30:28 
ULB: I go about with darkened skin but not because of the sun;
UDB: I go about very discouraged;

These have different interpretations, both of qoder, and of the relationship of the sun to the first part of the phrase.
Perhaps the UDB could be made like the ULB.

**Comment by TomWarren** [comment]
The Qal of this verb means "being dark" as by the clouds blocking the sun. I think the UDB is ok.  The idea of skin color is highly speculative.

The ULB of JOB 30:28 now reads: 
\v 28 I have gone about like one who was living in the dark, 
\q but not because of the sun;
\q I stand up in the assembly and cry for help.

Thanks,
Tom
