### ISSUE TITLE
Luk 13:25 UDB - "God = the owner of a house"

### ISSUE THREAD

**Issue by lrsallee** [Door43/udb-en#20]
This appears to be a continuation of the story of the house with the narrow door in the previous verses. The ULB is clear, but the indefinite "a house" of the UDB makes it sound like a completely different story. At the least, I believe this should be "the house" or "that house" to link it to the previous house with the narrow door.

I am a little uneasy about so clearly stating that God is the owner, even though I agree with that interpretation. I can live with this, but I would have been more comfortable with the first two sentences being combined as:

"Some day the owner of that house will lock the door."

This would allow the reader to make the connection to God's role (or not), as was evidently the intent of Jesus when he said this.

**Comment by TomWarren** [comment]
Here is the rework: Luke 13:25 UDB

\v 25 After the owner of the house gets up and locks the door, you will stand outside and you will knock on the door. And you will beg the owner and say to him, 'Lord, open the door for us!' But he will reply, 'No, I will not open it, because I do not know you, and I do not know where you are from!'

Thanks Larry.
