### ISSUE TITLE
Jer 1:9 UDB Metaphor?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#202]
Jer 1:9a ULB Then Yahweh reached out with his hand, touched my mouth, and said to me
UDB Then _it was as though_ Yahweh touched my mouth and said

The phrase "it was as though" in the UDB indicates that God did not really touch Jeremiah's mouth. 
The only other version I see like this is Deibler's TFT.
Would we want to assume that Yahweh really did do this in a vision?
Could "it was as though" be deleted?

**Comment by hmw3** [comment]
I'm not sure where the analogy breaks down, but when we watch a movie and a character looks into the camera and speaks, we say that the character spoke to us. At the very least Yahweh reached out in the vision. I don't think we need to let precise theology get in the way here. it seems to me it was a 3D sight sound and sense vision.


What really defies description is what happens when the coals touch Isaiah's lips -- did they burn, or did he get off like Shadrach, Meshach, and Abednego?


________________________________

**Comment by SusanQuigley** [comment]
So does that mean that "it was as though" can be deleted from the UDB? 

Or are you saying that even if it was a vision, God did not really do it, so "it was as though" God did it?

**Comment by hmw3** [comment]
I'd say God did it. Maybe there's enough of a battle going on in the theological world that a dissenting voice should be included in a note. But the reader of the translation should understand that as far as the visionary is concerned, it happened, or at least he wrote as though it happened.


Sez I.

________________________________

**Comment by SusanQuigley** [comment]
Here's what I have for a note. Because the UDB has "it was as though," that explanation comes first. It implies that that is the preferred interpretation.

**Then Yahweh reached out with his hand, touched my mouth** - Possible meanings are this is a metaphor representing Yahweh giving Jeremiah special authority to speak. AT: "Then it was as though Yahweh touched my mouth" (UDB) or 2) Jeremiah was seeing a vision and Yahweh actually did this as a symbolic act of giving Jeremiah authority to speak. AT: "Then Yahweh touched my mouth with his hand" (See: Metaphor and Symbolic Action)

**Comment by hmw3** [comment]
Bingo. You just need to add "1)" in the appropriate place.

________________________________

**Comment by SusanQuigley** [comment]
Oops. Thanks.
