### ISSUE TITLE
Jer 2:34 UDB Although

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#204]
UDB **Although** you have on your clothes the blood of poor people whom you have murdered,
people who were innocent! You did not catch them robbing you, but you chose to treat her wickedly.

The word "Although" seems to be a leftover from the TFT when 34 and 35 were one sentence. 
It would be good to delete it. Perhaps "In addition," or "also" could be used.
**In addition** you have on your clothes the blood of poor people 
or
You **also** have on your clothes the blood of poor people

**Comment by TomWarren** [comment]
Compare ULB JER 2:34-35 which reads:
\v 34 The blood that was the life of innocent, poor people has been found on your clothes.
\q These people were not discovered in acts of burglary, but still you defend yourselves.

\s5
\q
\v 35 You say, 'I am innocent; surely his anger has turned away from me.'
\q But look! I will bring down judgment on you because you say, 'I have not sinned.'

The UDB of JER 2:3-35 now reads:
\v 34 You also have the blood of poor people on your clothes; the very people you have murdered;
\q2 people who were innocent! You did not catch them robbing you!

\s5
\q1
\v 35 Yet you say, 'I have done nothing wrong!
\q2 I am sure that Yahweh will not be angry with me for much longer.'
\q1 But I will punish you severely
\q2 for claiming that you have not sinned.

Thanks, 
TW

**Comment by SusanQuigley** [comment]
Is the ULB "but still you defend yourselves" at the end of 2:34 implied info made explicit? Does it refer to them claiming that they are innocent as a  defense against God who would judge them?

**Comment by TomWarren** [comment]
That was to handle the chunk. The sentence broke at the end of that chunk but it continued to the next chunk. This was our way of preserving the meaning of the text across a chunk.  It is a bit cludgie, but it does keep things together, and the reader should be helped, we hope. 

If the chunk wasn't breaking up the sentence, it wouldn't be needed.

Tom

**Comment by SusanQuigley** [comment]
What would you think of dropping "but still you defend yourselves" at the end of 34,
and starting 35 with "Yet"? 

34The blood that was the life of innocent, poor people has been found on your clothes.
These people were not discovered in acts of burglary.
35 **Yet you** say, 'I am innocent; surely his anger has turned away from me.'

The implication of 34b is that if those who were killed had been discovered in acts of burglary, then perhaps those who killed them would not be guilty. But since they were not burglars, killing them was murder.

**Comment by TomWarren** [comment]
Good fix.
The ULB for JER 2:34 now reads:
\v 34 The blood that was the life of innocent, poor people has been found on your clothes.
\q Yet you say, 'These people were not discovered in acts of burglary.'

Thanks Susan, 

Tom

**Comment by SusanQuigley** [comment]
Oops. That's not quite what I meant.
34b is part of God's accusation against those who murdered the poor; It should not say "Yet you say" in 34b.
 The "you say" is part of v. 35. I meant for "Yet" to be at the beginning of v 35. 

34The blood that was the life of innocent, poor people has been found on your clothes.
These people were not discovered in acts of burglary.
35 **Yet you say,** 'I am innocent; surely his anger has turned away from me.'

**Comment by TomWarren** [comment]
Ah, thanks, Sorry for the zippy reading. 

The ULB of JER 2:34-35 now read:
\v 34 The blood that was the life of innocent, poor people has been found on your clothes.
\q These people were not discovered in acts of burglary.

\s5
\q
\v 35 Yet you say, 'I am innocent; surely his anger has turned away from me.'
\q But look! I will bring down judgment on you because you say, 'I have not sinned.'

**Comment by SusanQuigley** [comment]
That's it. Thank you.
