### ISSUE TITLE
Jer 2:37 led to Egypt

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#206]
UDB **They will capture you, and you will be their prisoners,
led to Egypt**, very ashamed with your hands on your heads.

ULB: You will also go out from there dejected, with your hands on your head,

I don't see any versions (other than TFT) that indicate that they would be led _to_ Egypt. 
Other versions seem to indicate that they would _leave_ Egypt.

**Comment by TomWarren** [comment]
Begin with
The UDB of JER 2:37 now reads:
\v 37 They will capture you, and you will be their prisoners,
\q2 very ashamed with your hands on your heads.
\q1 That will happen because Yahweh has rejected those nations that you are relying on,
\q2 and they will not be able to help you at all."
The ULB of JER 2:37 now reads:
\v 37 You will also go out from there dejected, with your hands on your head,
\q for Yahweh has rejected the ones whom you trusted, so you will not be helped by them."
