### ISSUE TITLE
Jer 3:23 UDB from all the other nations

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#209]
UDB: 
We did not get any help from the idols that we worshiped on the hilltops,
**we did not get any help from all the other nations**. 
We now recognize that Yahweh our God is the only way Israel will be saved!

ULB
Surely lies come from the hills, **a confusing noise from the mountains;**
surely Yahweh our God is the salvation of Israel.

Could **UDB** "we did not get any help from all the other nations" be changed to something like one of these?
we did not get any help from the gods on the mountains
we did not get any help from the gods of other nations
we did not get any help from from worshiping idols so noisily on the mountains

**Comment by TomWarren** [comment]
The UDB of JER 3:23 now reads after some editing: 
\v 23 When we worshiped idols on the mountains, we did not get any help. 
\q2 Even though we shouted very loudly in our worship, every promise we believed turned out to be lies and only lies. 
\q1 We now know that trusting in Yahweh our God is the only way Israel will be rescued!

Thanks,

TW
