### ISSUE TITLE
Jer 6:7  UDB backslash code error

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#213]
**q1** 7Its people keep doing wicked deeds,

The q1 shows up in the UDB just before the verse marker.

**Comment by TomWarren** [comment]
Here is that section, with repair:
\v 6 Yahweh, the commander of the armies of angels in heaven, says this,
\q1 "I will command those soldiers to cut down the trees outside Jerusalem
\q2 and to build ramps up to the top of the city walls!
\q1 This city must be punished
\q2 because everyone there continually oppresses others.
\q1
\v 7 Its people keep doing wicked deeds,
\q2 just as a well keeps producing water.
\q1 The noise from people doing violent and destructive actions is heard everywhere.
\q2 I continually see people who are suffering and wounded.
\q1
