### ISSUE TITLE
Amo 3:9 UDB  I said this to the leaders of Samaria:

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#219]
Amor 3:9 UDB 
**I said this to the leaders of Samaria:**
Send this message to the leaders in the city of Ashdod and in Egypt:
"Come to the hills of Samaria
and see the way that their leaders are causing people in that city to be terrified,
and the way that they are causing the people to suffer!"
10Yahweh says that the people there do not know how to do things that are right.
Their homes are filled with valuable things that they have stolen or taken violently from others.

I do not believe that Amos said this to the leaders of Samaria. It would not make sense for him to tell the leaders of Samaria to send a message to their enemies (the leaders of Ashdod and Egypt) saying how bad the people of Samaria are. Could **I said this to the leaders of Samaria:** be deleted?

**Comment by TomWarren** [comment]
The UDB of AMO 3:9  has been edited and now reads:

\v 9 Proclaim to the people who guard the strongholds in Ashdod,
\q2 and to those who protect the fortresses in the land of Egypt, and say this,
\q1 "Come together on the hills of Samaria,
\q2 and see how much the people in that city are frightened,
\q2 and see the way the people are suffering because of what they are doing to each other!"
