### ISSUE TITLE
Amo 3:15 UDB Missing phrase - Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#220]
I will cause the houses that they live in during the winter to be torn down.
Beautiful big houses and houses that are decorated with ivory will be destroyed.

The UDB doesn't mention the summer houses being destroyed.

**Comment by TomWarren** [comment]
The UDB of AMO 3:15 was edited to include the missing phrase, and it now reads:
\v 15 I will cause the houses that they live in during the winter to be torn down.
\q2 and the houses they live in during the summer, they also will be torn down.
\q2 Beautiful big houses and houses that are decorated with ivory will be destroyed.
\q1 That will surely happen because I, Yahweh, have said it!"

Thanks Susan,

Tom

**Comment by SusanQuigley** [comment]
Thanks, Tom. Please also capitalize "and" at the beginning of the second sentence.

\v 15 I will cause the houses that they live in during the winter to be torn down.
\q2  **and** the houses they live in during the summer, they will also be torn down.

**Comment by TomWarren** [comment]
We are avoiding the initial "And" where we can. 
The UDB of AMO 3:15 now reads:
\v 15 I will cause the houses that they live in during the winter to be torn down;
\q2 and the houses they live in during the summer, they will also be torn down.
\q2 Beautiful big houses and houses that are decorated with ivory will be destroyed.
\q1 That will surely happen because I, Yahweh, have said it!"

**Comment by SusanQuigley** [comment]
Semicolon works. Thanks.
