### ISSUE TITLE
Lam 4:15 UDB Who shouted?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#228]
UDB **These prophets and priests shout**, "Stay away from us! Do not touch us!"

ULB: "Away! Unclean!" **people cried at them**. "Away! Away! Do not touch!"

Could the UDB be changed to be like the ULB, so that it is the people shouting at the prophets and priests?

**Comment by TomWarren** [comment]
The UDB of LAM 4:14-15 was changed to read:
\v 14 The priests and prophets wander through the streets
\q2 as though they were blind.
\q1 No one will touch them
\q2 because their clothes are stained with the blood of those innocent people.
\q1
\v 15 These people shouted at the priests and prophets, saying, 
\q2 "Stay away from us! Do not touch us!"
\q1 So the priests and prophets have fled from Israel,
\q2 and they wander around from one country to another,
\q2 but people in each country keep saying to them, "You cannot stay here!"
\q2 because their clothes are stained with the blood of those innocent people.

I standardized the phrase "priests and prophets" there were three variations. 
Thanks Susan, 

Tom
