### ISSUE TITLE
2TI1:4 UDB 

### ISSUE THREAD

**Issue by sea-liesch** [Door43/udb-en#23]
2TI1:4 UDB 

missing verse marker for 2 Tim 1:4 there is no verse marker

~Chuck

**Comment by TomWarren** [comment]
There is a verse marker in Github UDB, 2 Tim 1:4 

\v 4 I really want to see you because I remember how you cried for me. If I see you again, I will rejoice so much.

There is a known rendering issue in Translation Studio. The reader in TS may not pick up every verse marker. This is a known issue, as I understand it, and should be addressed in the next version.
