### ISSUE TITLE
2CH 26:18 UDB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#247]
They rebuked him and said to him, "Amaziah, **it is not right for you _are set apart_ to burn incense** to honor Yahweh.

It looks like the words "are set apart" do not belong.

**Comment by TomWarren** [comment]
The UDB of 2CH 26:18 now reads:
\v 18 They rebuked him and said to him, "Uzziah, it is not right for you to burn incense to Yahweh because you are not set apart to serve as a priest, and only a priest can burn incense to Yahweh. The priests are the descendants of Aaron our first high priest, and you are not one of them! You must leave immediately, because you have disobeyed Yahweh our God, and he will not honor you for what you have done!"

A bit of reworking. 
Thanks,

Tom
