### ISSUE TITLE
Mrk 10:7 UDB  missing single close quote

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#256]
UDB: That explains why God said, 'When a man marries, he must leave his parents and join with his wife. 8They should become so closely united that they are like one person. And the two people will be like one person. 9Because that is true, a man must not separate from his wife. God has joined them together and he wishes them to stay together!"

This needs a single close quote where the quote from Genesis ends. The way the second sentence in verse 8 is written, it looks like it is intended to be part of the quote from Genesis. So the close quote would go at the end of verse 8. 

In the ULB, the second sentence of verse 8 is a conclusion that Jesus drew from Genesis.This would be a way of rewording the second sentence of v 8 in the  UDB so that it is a conclusion that Jesus draws.
 So when a man marries a woman, the two of them become like one person.

That explains why God said, 'When a man marries, he must leave his parents and join with his wife. 8They should become so closely united that they are like one person.'  So when a man joins with his wife, the two of them become like one person. 9Because that is true, a man must not separate from his wife. God has joined them together and he wishes them to stay together!"

**Comment by TomWarren** [comment]
The UDB of MRK 10:5-9 checked for quotation marks:
\v 5 Jesus said to them, **LEVEL 1**"Your ancestors stubbornly wanted to be able to send their wives away. That is why Moses wrote that law.
\v 6 But when God first created people, he made them male and female.

\s5
\v 7 That explains why God said, **LEVEL 2** 'When a man marries, he must leave his parents and join with his wife.
\v 8 They should become so closely united that they are like one person. And the two people will be like one person.
\v 9 Because that is true, a man must not separate from his wife. God has joined them together and he wishes them to stay together!'" **LEVEL 2, LEVEL 1** Closed

That seems to get them all. 

Thanks Susan, 

Tom

**Comment by SusanQuigley** [comment]
Tom, putting that single close quote at the end of v. 9 implies that the content of v 9 is from Genesis. But it's not.

**Comment by TomWarren** [comment]
I continued editing it after it was posted. We are on the same page.
Tom

**Comment by SusanQuigley** [comment]
Ok. Thanks.
