### ISSUE TITLE
Heb 12:2  UDB  missing info?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#259]
UDB: And let us keep thinking about Jesus and give him all our attention. He endured the terrible suffering on the cross and he paid no attention to the people who tried to shame him. He did this because he knew how joyful God would make him later. He now sits at the place of highest honor beside the throne where God rules in heaven.

I don't see anything here about Jesus being the founder and perfecter of the faith.

**Comment by TomWarren** [comment]
Seems to have been left out. 
The UDB of HEB 12:2 now reads:
\v 2 And let us keep thinking about Jesus and give him all our attention. He is the one who leads us and he makes our faith complete. He is the one who endured the terrible suffering on the cross and he paid no attention to the people who tried to shame him. He did this because he knew how joyful God would make him later. He now sits at the place of highest honor beside the throne where God rules in heaven.

Something of that order (looking at the CEV for UDBism. 

Thanks Susan, 

Tom

**Comment by SusanQuigley** [comment]
Thank you.
