### ISSUE TITLE
REV 6:11 UDB "all the believers"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#36]
6:11 UDB They should be patient until the wicked people killed **all the believers who served the Lord with them.** These believers were those whom God wanted to die in just the same way that these others had died.

The UDB sounds to me like all the believers who served the Lord with them would be killed. I wonder if it should be changed to somehow indicate that there was a certain number of fellow servants that were appointed to die as they had. In my attempt below, I tried using "those of" to show that not all believers would be killed.

They should be patient until the wicked people finished killing those of the believers whom God wanted to die. Those believers served the Lord with them, and would die just as they had died.
OR
They should be patient until the wicked people finished killing those of the believers whom God wanted to die as they had died. Those believers were ones who served the Lord with them.

**Comment by TomWarren** [comment]
There were some edits to get here: 

**\v 11 Then God gave to each of them a white robe, and he told them to be patient a little longer. They should be patient until the number of those who also served the Lord with them—who were their brothers and sisters in Christ—would be killed just like they themselves had been killed because of their faith.**
