### ISSUE TITLE
Update URL in license.sfm

### ISSUE THREAD

**Issue by jag3773** [Door43/udb-en#4]
_From @sewhite on March 11, 2016 14:12_

I notice in License.sfm it says the work must be attributed with "Original work available at http://openbiblestories.com."  Is this the real URL? My browser said this did not exist, then it finally came up with the unfoldingword.org home page.

_Copied from original issue: unfoldingWord/udb-en#1_

**Comment by hharrissWA** [comment]
The link seems to be correct now. The link connects to a video about the question at hand (?).

**Comment by ChrisJarka** [comment]
@codemis this link is wrong. Can you fix it?

**Comment by hharrissWA** [comment]
I may be able to fix the link, but I do not know where it goes. If I can get a link to the page where the link, https://unfoldingword.org/bible/, is found, I can simply copy and paste the correct link there (maybe?). 
Can someone send me the link to the page where the http://openbiblestories.com link is found, the one which should be the unfolding word link above?

Otherwise, I'm not sure how fix the link. If you need another word for "link," however, I might be able to help, for sure. :)  

Thanks,
Harry

**Comment by codemis** [comment]
@ChrisJarka Sorry, but I do not know anything about the license.sfm file.  Where can I find it?

**Comment by TomWarren** [comment]
@ChrisJarka this discussion is not really a text link. Should it be directed elsewhere?

**Comment by TomWarren** [comment]
@richmahn this discussion has been up for a while, and it is not text related. Could it be closed?

**Comment by TomWarren** [comment]
@jag3773  This issue is not going to be resolved by anyone on this. Could this be closed?
Thanks,

**Comment by hharrissWA** [comment]
Fine with me to close it.


C. Harry Harriss

Associate Editor, Unfolding Word Bible

Translation Consultant (in training)

Wycliffe Associates and Wycliffe India

harry_harriss@wycliffeassociates.org<mailto:harry_harriss@wycliffeassociates.org>

662-890-5637 home


________________________________
