### ISSUE TITLE
Rev 14:16 placed

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#44]
UDB: Then the one * placed his sickle on the earth
This is missing "who was sitting on the cloud" where I put the asterisk.
The verb "placed" in the UDB is more literal than "swung" in the ULB and makes for a strange picture.

**Comment by TomWarren** [comment]
UDB Rev 14:14-16 now reads:
\p
\v 14 Then I saw another surprising thing. It was a white cloud, and on the cloud someone was sitting who looked like the Son of Man. He was wearing a golden crown on his head. In his hand he held a sharp sickle.
\v 15 Still another angel came out of the temple in heaven. In a loud voice, he said to the one who was sitting on the cloud, "The time has come to reap the grain on the earth, so with your sickle reap the grain because the grain is ripe."
\v 16 Then **the one who was sitting on the cloud** placed his sickle on the earth and did all the work.

**Comment by TomWarren** [comment]
The second issue is the ULB Rev 14:16
ἔβαλεν is to cast or to throw (ballo). So to swing his sickle (as a sickle is used) makes sense. And the last phrase is mistranslated. καὶ  ἐθερίσθη  ἡ  γῆ.  "and the earth was harvested" is correct. 

\v 16 Then the one who was sitting on the cloud swung his sickle over the earth, and the earth was harvested.

**Comment by SusanQuigley** [comment]
Thank you, Tom.

**Comment by TomWarren** [comment]
I reworked the passive voice in the UDB to read:

"and he harvested the earth."

Same idea, but in active voice.
