### ISSUE TITLE
Rev 19 UDB Too much indenting

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#51]
Rev 19:1-8 UDB is all indented. I think it would be better to indent only the quotes when they are poetic, not John's whole narration.

**Comment by TomWarren** [comment]
The USFM is hard to discern here, but this is the UDB at Rev 19:1-8

1After these things I heard what sounded like a huge crowd in heaven. They were shouting things like,
     "Hallelujah! He has saved us!
      He is glorious and mighty!
2   Praise him because he judges truly and justly!
     He has punished the very evil city that was like a prostitute because their people persuaded the           other people of earth to act immorally as they did.
     Praise him because he has punished them for murdering his servants!"
3 The crowd shouted a second time, saying,
     "Hallelujah! The smoke of the fire that is burning that city will rise forever!"
4 The twenty-four elders and the four living creatures prostrated themselves and worshiped God, who sits on the throne. They said:
     "It is true! Hallelujah!"
5 Someone spoke from the throne and said,
     "All you who are his servants, praise our God!
     All you who honor him, whether you are important or not, everyone praise him!"
6 Then I heard something like the noise of a huge crowd of people, like the sound of a huge waterfall, and like the sound of loud claps of thunder. They were shouting:
     "Hallelujah! Our Lord God, the Almighty One, reigns!
7      We should rejoice, we should be extremely glad, and we should honor him
             because it is now time for the Lamb to be united with the woman he is marrying. She has           made herself ready.
8   God has permitted her to dress herself in fine linen, bright and clean.
            Fine, bright, and clean linen represents the righteous actions of God's people."
